name: example
description: Flame Oxygen example

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

# to update use flutter pub upgrade --major-versions
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flame_oxygen:
    path: packages/flame_oxygen
  shared_preferences: ^2.0.8
  json_annotation: ^4.3.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  # To build use flutter pub run build_runner build
  universal_io: ^2.0.4
  uuid: ^3.0.5
  equatable: ^2.0.3
  collection: ^1.15.0
  quiver: ^3.0.0
  path_to_regexp: ^0.4.0
  recase: ^4.0.0
  flutter_portal: ^0.4.0
  url_launcher: ^6.0.12
  get_it: ^7.2.0
  flame: ^1.0.0-releasecandidate.16
  flame_forge2d: ^0.8.2-releasecandidate.15
  stacked: ^2.2.7
  # flame_flare: ^0.1.0
  flame_tiled: 1.0.0-releasecandidate.15

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  build_runner: ^2.1.2
  flutter_lints: ^1.0.4
  flutter_gen: ^4.0.0
  flutter_gen_runner: ^4.0.0

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/icons/logo.png"
  ios: true
  android: true
  remove_alpha_ios: true

# For information see the following page:
# https://pub.dev/packages/flutter_gen
flutter_gen:
  # output: lib/gen/ # Optional (default: lib/gen/)
  # line_length: 80 # Optional (default: 80)
  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
